### ISSUE TITLE
Обновить руби/рельсы до 2.4.0 / 4.2.8

### ISSUE THREAD

**Issue by gambala** [gambala/ruby_courses#39]
Я могу обновить локально и кинуть пул-реквест, но руби дополнительно нужно обновить и на сервере, к серверу доступа у меня нет. 😺

Как лучше поступить?

**Comment by Freika** [comment]
@gambala я постараюсь на этой неделе обновить там руби, тогда можно будет закинуть ПР :)

**Comment by gambala** [comment]
Готово. Руби 2.6.1 и Рельсы 5.2.4
