### ISSUE TITLE
Отображать отзывы о курсе в хронологическом порядке

### ISSUE THREAD

**Issue by installero** [gambala/ruby_courses#52]
Сейчас: https://rubycourses.ru/courses/161

![Screenshot from 2020-07-08 19-56-37](https://user-images.githubusercontent.com/42387/86947937-2972ed00-c155-11ea-9e19-197345de0de9.png)

Решать, свежие сверху или старые сверху — уважаемым авторам проекта

**Comment by gambala** [comment]
Можно пока сделать новые сверху, старые снизу. Переключение я бы внедрил на уровне пользователей (сортировка на странице курса), нежели на уровне автора курса

**Comment by gambala** [comment]
Done by #55
