### ISSUE TITLE
Не работает функция восстановления пароля

### ISSUE THREAD

**Issue by installero** [gambala/ruby_courses#53]
При попытке восстановления пароля вижу такое:

![Screenshot from 2020-07-08 19-58-45](https://user-images.githubusercontent.com/42387/86948191-76ef5a00-c155-11ea-99a2-c7d7cff1768d.png)

1. Зайти [сюда](https://rubycourses.ru/users/password/new)
2. Ввести свой email
3. Увидеть ошибку

Возможно, моего адреса нет в базе, тогда сообщение об ошибке просто надо поправить.

**Comment by gambala** [comment]
Fixed by #54
